### ISSUE TITLE
서버비용 긴축

### ISSUE THREAD

**Issue by junu-kk** [SoundPicker/SoundPicker-Server#15]
## 배경
AWS 프리티어가 끝나고 한 달에 서버비 5만원이 과금되는 것을 두고 볼 수 없다.
(한달에 EC2 10달러, RDS 20달러, S3 X)

## 계획
- Phase 1: AWS 내에서 돈이 제일 많이 드는 RDS를 EC2 내 DB를 따로 설치해 없앤다.
- Phase 2: AWS에서 무료 클라우드 서비스인 오라클 클라우드로 이동해, 별도의 PaaS 활용 없이 서버 한 대에 모든 기능을 몰아넣는다.

### Phase 1
- [x] ~EC2 scale-down을 시도했으나..~
  - 1코어에 메모리 500MB로 웹서버와 DB가 돌아가지 못한다. 서버 스펙은 그대로 유지한다.
- [x] EC2 내 MySQL 설치
- [x] RDS MySQL -> EC2 MySQL 복제
- [x] 서버 접속정보 로컬로 수정해 재배포
- [x] 정상동작 확인 후 RDS 삭제

### Phase 2
- [ ] S3 스토리지 대신 파일시스템 참조하도록 로직 변경
- [ ] AWS 백업
  - [ ] DB 데이터 복제
  - [ ] audios 파일 통째로 다운로드 후 로컬머신에 넣고, DB애 저장된 path 변경
- [ ] 오라클 클라우드 셋업
  - [ ] 계정 발급 (마스터카드 신용카드가 있어야 하나봄 -_-.. 체크 X)
  - [ ] 배포
